# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'metodum' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for metodum
pod 'Firebase/Core'
pod 'Firebase/Firestore' 
pod 'Firebase/Auth'
pod 'Firebase/Storage' 
pod 'Firebase/Messaging'
pod 'GooglePlaces'

end
